version: '2'
services:
  app:
    build: .
    tty: true
    # depends_on:
    #   - phantomjs
    environment:
      # - PHANTOMJS_HOST=http://phantomjs
      # - PHANTOMJS_PORT=8910
    command: rake browbeat:check:production
  #
  # phantomjs:
  #   image: wernight/phantomjs:2.1.1
  #   expose:
  #     - "8910"
  #   command: phantomjs --webdriver 8910
