docker-defaults: &docker-defaults
  docker:
    - image: docker:18.05.0-ce-git
  working_directory: ~/app

version: 2
jobs:
  build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose==1.16.1
      - run:
          name: Pull docker images
          command: |
            script/pull_docker.sh
      - run:
          name: Build
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Test
          command: |
            touch secrets.env
            docker-compose run test
      - run:
          name: Docker login
          command: |
            docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push docker images
          command: |
            script/push_docker.sh
