docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git
  working_directory: ~/app

version: 2
jobs:
  build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull docker images
          command: |
            script/pull_docker.sh
      - run:
          name: Build
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Test
          command: |
            touch secrets.env
            docker-compose run test
      - run:
          name: Docker login
          command: |
            docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push docker images
          command: |
            script/push_docker.sh
