website:
  name: Library.nyu.edu
  status_page_id: thynp2429mrl
login:
  name: Login
  status_page_id: lsz65k52nb8j
eshelf:
  name: E-Shelf
  status_page_id: j97ssf4rf48g
primo:
  name: BobCat (Book & More, Course Reserves)
  status_page_id: zx6y50m1jdjv
aleph:
  name: BobCat Standard
  status_page_id: 1ml524b3pf1h
getit:
  name: GetIt (Journals, Record detail page)
  status_page_id: kl0xwlyl4y6n
arch:
  name: The Arch (Articles & Databases, Databases A-Z)
  status_page_id: dnxb1np2b5zy
illiad:
  name: Interlibrary Loan (ILL)
  status_page_id: r7sjhcjpwc3h
room:
  name: Room Reservation System
  status_page_id: 04tq5pv1m4tw
special_collections:
  name: Archival Collections
  status_page_id: 24mxy5m1c505
privileges:
  name: Privileges Guide
  status_page_id: zh4m03cjhtxl
marli:
  name: MaRLI (Manhattan Research Library Initiative)
  status_page_id: tfhq22gtmld9
ezborrow:
  name: EZBorrow
  status_page_id: 9hgcdbqnd832
ezproxy:
  name: EZProxy
  status_page_id: q23q1ggvgj60
