website:
  name: Library.nyu.edu
  status_page_production_id: nrp5lmcnw0gn
  status_page_staging_id: 14qz22399vlk
login:
  name: Login
  status_page_production_id: ghc0gj9shv49 
  status_page_staging_id: kndn13tq3sr3
eshelf:
  name: E-Shelf
  status_page_production_id: k5thfpqj0qmv 
  status_page_staging_id: k1pgq5wb19rh
primo:
  name: BobCat (Book & More, Course Reserves)
  status_page_production_id: kbhjbx6bh3dj
  status_page_staging_id: kl8yq08ggfn7
aleph:
  name: BobCat Standard
  status_page_production_id: cxzdybjsqt7q
  status_page_staging_id: 79jvlh4jpfhf
getit:
  name: GetIt (Journals, Record detail page)
  status_page_production_id: gvz77sjv89rw
  status_page_staging_id: p0nf864q6d6y
arch:
  name: Salon (Persistent links)
  status_page_production_id: nbm2m5gfbbgr
  status_page_staging_id: qp1gmyztj4bh
illiad:
  name: Interlibrary Loan (ILL)
  status_page_production_id: 1sx8th52njg4
  status_page_staging_id: rp5p3l5d977h
rooms:
  name: Room Reservation System
  status_page_production_id: r5rq37pqcf59
  status_page_staging_id: hk1mzhg83h87
special_collections:
  name: Archival Collections
  status_page_production_id: 9rc5mf9w2dm6
  status_page_staging_id: vwtbxnkz610f
privileges:
  name: Privileges Guide
  status_page_production_id: 3fbxtn7vfj5h
  status_page_staging_id: 9kd8468h7cxz
marli:
  name: MaRLI (Manhattan Research Library Initiative)
  status_page_production_id: dx2kscx837zv
  status_page_staging_id: 5ct9z5v91t7n
ezborrow:
  name: EZBorrow
  status_page_production_id: 6l6kmr03bp6n
  status_page_staging_id: mfkyzv14km1s
ezproxy:
  name: EZProxy
  status_page_production_id: 459g43pc5pxr
  status_page_staging_id: zvwwcgzmzf3y
