module Browbeat
  module Helpers
    module ScrubFigsHelper
      KEYS_TO_SCRUB = %w[SHIBBOLETH_USERNAME SHIBBOLETH_PASSWORD SHIBBOLETH_STAGING_USERNAME SHIBBOLETH_STAGING_PASSWORD ALEPH_USERNAME ALEPH_PASSWORD SAUCE_USERNAME SAUCE_ACCESS_KEY STATUS_PAGE_API_KEY STATUS_PAGE_PAGE_ID STATUS_PAGE_STAGING_PAGE_ID SELENIUM_DOWNLOAD_DIRECTORY AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY]

      def scrub_figs(text)
        KEYS_TO_SCRUB.each do |key|
          text = text.gsub(ENV[key], 'X' * 5) if ENV[key]
        end
        text
      end
    end
  end
end
